# Generated by Django 2.1.3 on 2018-12-18 06:32

from django.db import migrations, models
import django.db.models.deletion
import part1.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('survey', part1.fields.ThumbnailImageField(upload_to='survey/%Y/%m')),
                ('data', models.FileField(blank=True, null=True, upload_to='data/%d')),
                ('resized_survey', models.ImageField(blank=True, null=True, upload_to='resized_survey/%d')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Unziped_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='unzip/%d')),
                ('meta_survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='part1.MetaSurvey')),
            ],
        ),
    ]
