# Generated by Django 2.1.3 on 2018-12-01 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metasurvey',
            name='survey',
            field=models.ImageField(blank=True, null=True, upload_to='survey/%d'),
        ),
    ]
