# Generated by Django 2.1.3 on 2018-12-19 15:25

from django.db import migrations
import part1.fields


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metasurvey',
            name='survey',
            field=part1.fields.ThumbnailImageField(upload_to='survey/'),
        ),
    ]
