# Generated by Django 2.1.3 on 2018-12-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0002_auto_20181202_0424'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSurvey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='survey/data/%d')),
            ],
        ),
    ]
