# Generated by Django 2.1.3 on 2018-12-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0003_datasurvey'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataSurvey',
        ),
        migrations.AddField(
            model_name='metasurvey',
            name='data',
            field=models.FileField(blank=True, null=True, upload_to='data/%d'),
        ),
    ]
